# Generated by Django 4.2.5 on 2023-09-14 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Only string characters are allowed.', regex='^[a-zA-Z\\s]+$')])),
            ],
            options={
                'db_table': 'person',
                'ordering': ['-name'],
            },
        ),
    ]
